= REST Implementations for User Management Edge Microservice
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>
ifdef::env-github[:USER: SMARTRACTECHNOLOGY]
ifdef::env-github[:REPO: smartcosmos-edge-user-devkit]
ifdef::env-github[:BRANCH: master]

image::https://jenkins.smartcosmos.net/buildStatus/icon?job={USER}/{REPO}/{BRANCH}[Build Status, link=https://jenkins.smartcosmos.net/job/{USER}/job/{REPO}/job/{BRANCH}/]

The SMART COSMOS User Management (DevKit) API provides an implementation of
SMART COSMOS Tenants, Users, Roles, and Authorities suitable for testing and
development. While this API and the backing code may be useful as a template
for a production-quality implementation of these SMART COSMOS metaphors, it
is in no way intended for production use. From the SMART COSMOS DevKit documentation:

NOTE: SMART COSMOS DevKit is designed for learning, testing, and evaluation
of the SMART COSMOS platform. It is not intended for production use, and it is
inherently insecure due to its reliance on a JKS key pair for which the
https://github.com/SMARTRACTECHNOLOGY/smartcosmos-auth-server/blob/master/src/main/resources/smartcosmos.\jks[secret key]
is publicly available and cannot be replaced, and its use of the primary Devkit
database as a store for user and account data. To establish a secure, production-ready
SMART COSMOS environment, consult your SMARTRAC Technology, Inc. customer representative.

=== A Note About Tenants, Users, Roles, and Authorities

SMART COSMOS Objects has been designed from the outset to support multi-tenancy.
A Tenant has one or more Users (a default user with the Admin Role is created as part
of any Tenant creation), and a User has one or more Roles. Each Role contains zero
or more Authorities, and these are the Authorities referred to below.

The SMART COSMOS DevKit creates two Roles by default: Admin and User. Both Roles
contain all of the authorities listed below; the difference between the two Roles
is that a User with the Admin Role can create and edit Users.

The developer can customize Roles and Authorities as needed, but the Authorities
listed in the API documentation are absolutely required by any User to execute the
relevant CRUD operations.

=== API Documentation

For detailed information on the SMART COSMOS Metadata API, please consult the link:API.adoc[API document].

=== Next Steps

To learn more about SMART COSMOS, have a look at link:https://github.com/SMARTRACTECHNOLOGY/smartcosmos-devkit#smart-cosmos-getting-started-guide[SMART COSMOS Getting Started Guide].


== Copyright and License
Code and documentation copyright 2016 Smartrac Technology Fletcher, Inc.  Code released under link:LICENSE[Apache 2.0 License].
