= REST Implementations for User Management Edge Microservice
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>
:version: 3.0.0-SNAPSHOT
ifdef::env-github[:USER: SMARTRACTECHNOLOGY]
ifdef::env-github[:REPO: smartcosmos-edge-user-devkit]
ifdef::env-github[:BRANCH: master]

Microservice which provides basic management functionality for tenants, user and roles. This services is not recommended for production purposes.

== License
This is a private licensed repository, and as such, should not be shared publicly.

== Authorities

=== Tenant Authorities

- https://authorities.smartcosmos.net/tenants/read
- https://authorities.smartcosmos.net/tenants/update

=== User Authorities

- https://authorities.smartcosmos.net/users/create
- https://authorities.smartcosmos.net/users/read
- https://authorities.smartcosmos.net/users/update
- https://authorities.smartcosmos.net/users/delete

=== Role Authorities

- https://authorities.smartcosmos.net/roles/create
- https://authorities.smartcosmos.net/roles/read
- https://authorities.smartcosmos.net/roles/update
- https://authorities.smartcosmos.net/roles/delete

== REST API

<<tenants, *Available methods for tenants*>>

|====================
|Endpoint|REST API|Required Authority
|<<tenantcreate1, Create>>|`POST /tenants`|none
|<<tenantupdate1, Update, Validate OTP Authentication>>|`PUT /tenants/{urn}`|https://authorities.smartcosmos.net/tenants/update
|<<tenantread1, Find by URN>>|`GET /tenants/{urn}`|https://authorities.smartcosmos.net/tenants/read
|<<tenantread2, Find by Name>>|`GET /tenants/?name={name}`|https://authorities.smartcosmos.net/tenants/read
|====================

<<users, *Available methods for users*>>

|====================
|Endpoint|REST API|Required Authority
|<<usercreate1, Create>>|`POST /users`|https://authorities.smartcosmos.net/users/create
|<<userupdate1, Update>>|`PUT /users/{urn}`|https://authorities.smartcosmos.net/users/update
|<<userread1, Find by URN>>|`GET /users/{urn}`|https://authorities.smartcosmos.net/users/read
|<<userread2, Find by Name>>|`GET /users/?name={name}`|https://authorities.smartcosmos.net/users/read
|<<userdelete1, Delete>>|`DELETE /users/{urn}`|https://authorities.smartcosmos.net/users/delete
|====================

<<roles, *Available methods for roles*>>

|====================
|Endpoint|REST API|Required Authority
|<<rolecreate1, Create>>|`POST /roles`|https://authorities.smartcosmos.net/roles/create
|<<roleupdate1, Update>>|`PUT /roles/{urn}`|https://authorities.smartcosmos.net/roles/update
|<<roleread1, Find by URN>>|`GET /roles/{urn}`|https://authorities.smartcosmos.net/roles/read
|<<roleread2, Find by Name>>|`GET /roles/?name={name}`|https://authorities.smartcosmos.net/roles/read
|<<roledelete1, Delete>>|`DELETE /roles/{urn}`|https://authorities.smartcosmos.net/roles/delete
|====================

=== JSON Fields for Tenants
[width="100%",options="header"]
|====================
| Field | Format | Default | Required | Description
| `urn` | String representation of a tenant identifier in a common scheme, e.g. `urn:tenant:uuid:<UUID>` | generated, value and format depend on the persistence layer implementation | | will be generated
| `name` | String | | yes | Name of the tenant organization (e.g. `Example Company`)
| `active` | boolean |  true | no |
| `username` | String | | yes (for create) | Initial admin account
|====================

=== JSON Fields for Users
[width="100%",options="header"]
|====================
| Field | Format | Default | Required | Description
| `urn` | String representation of a user identifier in a common scheme, e.g. `urn:user:uuid:<UUID>` | generated, value and format depend on the persistence layer implementation | | will be generated
| `username` | String | | yes | login name, e.g. `bob@example.com`
| `emailAddress` | String | | no | e.g. `bob@example.com`
| `active` | boolean |  true | no |
| `givenName` | String |  | no |
| `surname` | String |  | no |
| `password` | String |  | no |
| `roles` | Array of String |  | yes | e.g. `Admin` or `User`
| `authorities` | Array of String |  | yes | e.g. `https://authorities.smartcosmos.net/things/read` or `https://authorities.smartcosmos.net/things/create`
| `tenantUrn` | String representation of the tenant identifier in a common scheme, e.g. `urn:tenant:uuid:<UUID>` |  | yes |
|====================

=== JSON Fields for Roles
[width="100%",options="header"]
|====================
| Field | Format | Default | Required | Description
| `urn` | String representation of a user identifier in a common scheme, e.g. `urn:role:uuid:<UUID>` | generated, value and format depend on the persistence layer implementation | | will be generated
| `name` | String | | yes | Unique name of the role, e.g. `Admin`
| `authorities` | Array of String |  | yes | e.g. `https://authorities.smartcosmos.net/things/read` or `https://authorities.smartcosmos.net/things/create`
| `tenantUrn` | String representation of the tenant identifier in a common scheme, e.g. `urn:tenant:uuid:<UUID>` |  | yes |
|====================

.**URN Scheme**
Note that the illustrated scheme for URNs is only for documentation purposes. There must not be any assumptions or expectations on the scheme in the REST layer. All URNs or identifiers are just `String` values in the scope of REST modules!

=== URL parameters
[width="100%",options="header"]
|====================
| Parameter | Format | Default | Description
| `name` | String | optional | Optional search parameter to filter the search result by `name` or `username`
|====================


=== API Endpoints

[[tenants]]
==== Tenant Endpoints

[[tenantcreate1]]
===== Create - `POST /tenants`

----
POST /tenants
----

*Example 1*
[source,json]
----
{
    "active": true,
    "name": "Example Company",
    "username": "waldo@example.com"
}
----

.Response
----
201 CREATED
----
[source,json]
----
{
    "urn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c",
    "admin": {
        "urn": "urn:user:uuid:34068f4d-12a5-4546-80f8-9f84b762db20",
        "username": "waldo@example.com",
        "password": "PleaseChangeMeImmediately",
        "roles": [
          "Admin"
        ],
        "tenantUrn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c"
    }
}
----

*Example 2*
[source,json]
----
{
    "name": "Example Company",
    "username": "waldo@example.com"
}
----

.Response
----
201 CREATED
----
[source,json]
----
{
    "urn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c",
    "admin": {
        "urn": "urn:user:uuid:34068f4d-12a5-4546-80f8-9f84b762db20",
        "username": "waldo@example.com",
        "password": "PleaseChangeMeImmediately",
        "roles": [
          "Admin"
        ],
        "tenantUrn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c"
    }
}
----

[[tenantupdate1]]
===== Update - `PUT /tenants/{urn}`

----
PUT /tenants/urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c
----
[source,json]
----
{
    "active": false,
    "name": "My Example Company"
}
----
.Response
----
204 NO CONTENT
----

[[tenantread1]]
===== Find by URN - `GET /tenants/{urn}`

----
GET /tenants/urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c
----
.Response
----
200 OK
----
[source,json]
----
{
    "urn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c",
    "active": true,
    "name": "My Example Company"
}
----

[[tenantread2]]
===== Find by Name - `GET /tenants/?name={name}`

----
GET /tenants?name=My%20Example%20Company
----
.Response
----
200 OK
----
[source,json]
----
{
    "urn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c",
    "active": true,
    "name": "My Example Company"
}
----

----
GET /tenants
----
.Response
----
200 OK
----
[source,json]
----
[
    {
        "urn": "urn:tenant:uuid:346e742e-2f1e-4d91-9ffe-7b38eec6219c",
        "active": true,
        "name": "My Example Company"
    },
    {
        "urn": "urn:tenant:uuid:f1e4ff26-2a5f-41c6-8533-4994cb2cceec",
        "active": true,
        "name": "Another Example Company"
    }
]
----


[[users]]
==== User Endpoints

[[usercreate1]]
===== Create - `POST /users`

----
POST /users
----

*Example 1*
[source,json]
----
{
    "active": true,
    "roles": [
        "User"
    ],
    "username": "bob@example.com",
    "emailAddress": "bob@example.com",
    "givenName": "Bob",
    "surname": "Smith"
}
----

.Response
----
201 CREATED
----
[source,json]
----
{
    "urn": "urn:user:uuid:68a76616-3748-4bc2-93c1-3940b47abb7f",
    "username": "bob@example.com",
    "password": "PleaseChangeMeImmediately",
    "roles": [
        "User"
    ],
    "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
}
----

*Example 2*
[source,json]
----
{
    "roles": [
        "User"
    ],
    "username": "bob@example.com"
}
----

.Response
----
201 CREATED
----
[source,json]
----
{
    "urn": "urn:user:uuid:68a76616-3748-4bc2-93c1-3940b47abb7f",
    "username": "bob@example.com",
    "password": "PleaseChangeMeImmediately",
    "roles": [
        "User"
    ],
    "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
}
----

[[userupdate1]]
===== Update - `PUT /users/{urn}`

----
PUT /users/urn:user:uuid:68a76616-3748-4bc2-93c1-3940b47abb7f
----
[source,json]
----
{
    "active": false,
    "password": "xyz1234567"
}
----
.Response
----
204 NO CONTENT
----

[[userread1]]
===== Find by URN - `GET /users/{urn}`

----
GET /users/urn:user:uuid:68a76616-3748-4bc2-93c1-3940b47abb7f
----
.Response
----
200 OK
----
[source,json]
----
{
    "urn": "urn:user:uuid:68a76616-3748-4bc2-93c1-3940b47abb7f",
    "active": true,
    "roles": [
        "User"
    ],
    "username": "bob@example.com",
    "emailAddress": "bob@example.com",
    "givenName": "Bob",
    "surname": "Smith",
    "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
}
----

[[userread2]]
==== Find by Name - `GET /users?name={name}`

----
GET /users
----
.Response
----
200 OK
----
[source,json]
----
[
    {
        "urn": "urn:user:uuid:68a76616-3748-4bc2-93c1-3940b47abb7f",
        "active": true,
        "roles": [
            "User"
        ],
        "username": "bob@example.com",
        "emailAddress": "bob@example.com",
        "givenName": "Bob",
        "surname": "Smith",
        "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
    },
    {
        "urn": "urn:user:uuid:af37520d-86ad-49fe-be25-92ce269fbda4",
        "active": true,
        "roles": [
            "Admin"
        ],
        "username": "jane@example.com",
        "emailAddress": "jane@example.com",
        "givenName": "Jane",
        "surname": "Smith",
        "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
    }
]
----

[[userdelete1]]
===== Delete - `DELETE /users/{urn}`

----
DELETE /users/urn:role:uuid:fcdf5432-49a8-45ef-96a2-94a022022860
----
.Response
----
204 NO CONTENT
----

[[roles]]
==== Roles Endpoints

[[rolecreate1]]
===== Create - `POST /roles/`

----
POST /roles/
----
[source,json]
----
{
    "name": "User",
    "authorities": [
        "https://authorities.smartcosmos.net/things/read"
    ]
}
----

.Response
----
201 CREATED
----
[source,json]
----
{
    "urn": "urn:role:uuid:fcdf5432-49a8-45ef-96a2-94a022022860",
    "name": "User",
    "active": true,
    "authorities": [
        "https://authorities.smartcosmos.net/things/read"
    ],
    "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
}
----

[[roleupdate1]]
===== Update - `PUT /roles/{urn}`

----
PUT /roles/urn:role:uuid:fcdf5432-49a8-45ef-96a2-94a022022860
----
[source,json]
----
{
    "name": "User",
    "authorities": [
        "https://authorities.smartcosmos.net/things/read"
    ]
}
----
.Response
----
204 NO CONTENT
----

[[roleread1]]
===== Find by URN - `GET /roles/{urn}`

----
GET /roles/urn:role:uuid:318a9fae-0218-486c-b9f6-86f76b2ff6af
----
.Response
----
200 OK
----
[source,json]
----
{
    "urn": "urn:role:uuid:318a9fae-0218-486c-b9f6-86f76b2ff6af",
    "name": "Admin",
    "active": true,
    "authorities": [
        "https://authorities.smartcosmos.net/things/read",
        "https://authorities.smartcosmos.net/things/create"
    ],
    "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
}
----

[[roleread2]]
===== Find by Name - `GET /roles?name={name}`

----
GET /roles
----
.Response
----
200 OK
----
[source,json]
----
[
    {
        "urn": "urn:role:uuid:318a9fae-0218-486c-b9f6-86f76b2ff6af",
        "name": "Admin",
        "active": true,
        "authorities": [
            "https://authorities.smartcosmos.net/things/read",
            "https://authorities.smartcosmos.net/things/create"
        ],
        "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
    },
    {
        "urn": "urn:role:uuid:fcdf5432-49a8-45ef-96a2-94a022022860",
        "name": "User",
        "active": true,
        "authorities": [
            "https://authorities.smartcosmos.net/things/read"
        ],
        "tenantUrn": "urn:tenant:uuid:69bb7c6a-a43b-493d-8e9d-e5a3ed65728a"
    }
]
----

[[roledelete1]]
===== Delete - `DELETE /roles/{urn}`

----
DELETE /roles/urn:role:uuid:fcdf5432-49a8-45ef-96a2-94a022022860
----
.Response
----
204 NO CONTENT
----

== Configuration

The user details service needs to be properly configured for the following purposes:

- accessing the user database

[source,yaml]
----
server:
  port: 45371

spring:
  datasource:
    url: jdbc:mysql://{dbServer}/{dbName}
    username: {dbUser}
    password: {dbPassword}
    driver-class-name: org.mariadb.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      # Edge User DevKit and User Details DevKit share the database scheme
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

smartcosmos:
  security:
    enabled: true

  endpoints:
    tenants:
      enabled: true
      create.enabled: true
      read:
        urn.enabled: true
        all.enabled: true
      update.enabled: true
    users:
      enabled: true
      create.enabled: true
      read:
        urn.enabled: true
        all.enabled: true
      update.enabled: true
      delete.enabled: true
    roles:
      enabled: true
      create.enabled: true
      read:
        urn.enabled: true
        all.enabled: true
      update.enabled: true
      delete.enabled: true
----
